version: '3'

services:
    backend:
        build: backend
        expose: 
            - ${APP_PORT}
        environment: 
            API_HOST: ${API_HOST}
            APP_PORT: ${APP_PORT}
        ports: 
            - ${APP_PORT}:${APP_PORT}
        volumes: 
            - ./backend:/backend
    frontend:
        build: frontend
        environment: 
            - REACT_APP_PORT=${REACT_APP_PORT}
        ports: 
            - ${REACT_APP_PORT}:${REACT_APP_PORT}
        expose: 
            - ${REACT_APP_PORT}
        volumes: 
            - ./frontend:/frontend
        links: 
            - backend